### ISSUE TITLE
agent craps out when /etc/issue is missing

### ISSUE THREAD

**Issue by phillmv** [appcanary/agent#95]
User on Ubuntu 14.04.3 couldn't get agent to boot; later discovered that he was missing /etc/issue. Putting that file in fixed it.

```
D0905 22:04:35.992993 22539 conf.go:50] Found, read server conf. 
panic: runtime error: index out of range

goroutine 1 [running]: 
github.com/appcanary/agent/agent.NewServer(0xc2080586c0, 0x943fc8) 
/Users/phillmv/code/go/src/github.com/appcanary/agent/agent/server.go:70 +0x86c 
github.com/appcanary/agent/agent.NewAgent(0x82da90, 0x1b, 0xc208032880, 0x0, 0x0, 0x0, 0x13) 
/Users/phillmv/code/go/src/github.com/appcanary/agent/agent/agent.go:17 +0xe7 
main.main() 
/Users/phillmv/code/go/src/github.com/appcanary/agent/main.go:55 +0x5bb
```

**Comment by ghedamat** [comment]
how was he missing that?

:/ anyway.. should probably handle that case..

**Comment by phillmv** [comment]
This is… not going to be a problem anymore.
